
-- Function 1 (Scalar Function)
--Question
-- Return the average feedback rating of a specific customer.

CREATE FUNCTION dbo.fn_AverageCustomerRating
(
    @CustomerID INT
)
RETURNS DECIMAL(4,2)
AS
BEGIN
    DECLARE @AvgRating DECIMAL(4,2);

    SELECT @AvgRating = AVG(CAST(rating AS DECIMAL(4,2)))
    FROM Feedback
    WHERE customer_id = @CustomerID;

    RETURN ISNULL(@AvgRating,0);
END;
GO


-- Execute
SELECT dbo.fn_AverageCustomerRating(6) AS Average_Rating;
GO

--Function 2 (Scalar Function)
--Question
-- Return total revenue generated by a specific service.

CREATE FUNCTION dbo.fn_ServiceRevenue
(
    @ServiceID INT
)
RETURNS DECIMAL(10,2)
AS
BEGIN
    DECLARE @Revenue DECIMAL(10,2);

    SELECT @Revenue = SUM(p.amount_paid)
    FROM Payments P
    INNER JOIN Orders O
        ON P.order_id = O.order_id
    INNER JOIN Order_Items OI
        ON O.order_id = OI.order_id
    WHERE OI.service_id = @ServiceID;

    RETURN ISNULL(@Revenue,0);
END;
GO

-- Execute
SELECT dbo.fn_ServiceRevenue(5) AS Total_Revenue;
GO

--Function 3 (Table-Valued Function)
--Question
-- Return all active coupons.

CREATE FUNCTION dbo.fn_ActiveCoupons()
RETURNS TABLE
AS
RETURN
(
    SELECT
        coupon_id,
        coupon_code,
        discount_percentage,
        expiry_date
    FROM Coupons
    WHERE expiry_date >= GETDATE()
);
GO

-- Execute
SELECT *
FROM dbo.fn_ActiveCoupons();
GO
